// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version: 16.0.0.0
//  
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
namespace EADotnetAngularGen.Templates.Client
{
    using System.Linq;
    using System.Text;
    using System.Collections.Generic;
    using CaseExtensions;
    using EADotnetAngularGen.Templates.Api;
    using System;
    
    /// <summary>
    /// Class to produce the template output
    /// </summary>
    
    #line 1 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public partial class EditComponentSpec : EditComponentSpecBase
    {
#line hidden
        /// <summary>
        /// Create the template output
        /// </summary>
        public virtual string TransformText()
        {
            this.Write("import { TestBed } from '@angular/core/testing';\r\nimport { BrowserAnimationsModule } from '@angular/platform-browser/animations';\r\nimport { of } from 'rxjs';\r\nimport { ");
            
            #line 11 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent } from './");
            
            #line 11 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("-edit.component';\r\nimport { ");
            
            #line 12 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(string.Join(", ", Model.Attributes.Cast<EA.Attribute>().Where(x=>!x.IsTypePrimitive()).Select(x=>x.Type).Concat(new string[]{Model.Name}).Select(x=> string.Format("{0}, {0}Service, {0}ServiceInterface", x)))));
            
            #line default
            #line hidden
            this.Write(" } from '../api';\r\nimport { MatDialogRef, MAT_DIALOG_DATA } from '@angular/material/dialog';\r\n\r\ndescribe('");
            
            #line 15 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent', () => {\r\n  \r\n   \r\n  let matDialogRefSpy : jasmine.SpyObj<MatDialogRef<");
            
            #line 18 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent>> | null = null;\r\n\r\n  let ");
            
            #line 20 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy: jasmine.SpyObj<");
            
            #line 20 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ServiceInterface> | null = null;\r\n\r\n");
            
            #line 22 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 foreach (EA.Attribute attribute in Model.Attributes.Cast<EA.Attribute>().Where(x=>!x.IsTypePrimitive())) { 
            
            #line default
            #line hidden
            this.Write("  let ");
            
            #line 23 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy: jasmine.SpyObj<");
            
            #line 23 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type));
            
            #line default
            #line hidden
            this.Write("ServiceInterface> | null = null;\r\n\r\n");
            
            #line 25 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n\r\n  beforeEach(async () => {\r\n\r\n  matDialogRefSpy = jasmine.createSpyObj<MatDialogRef<");
            
            #line 30 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent>>(['close']);\r\n\r\n  ");
            
            #line 32 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy = jasmine.createSpyObj<");
            
            #line 32 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("ServiceInterface>(['");
            
            #line 32 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("IdGet', '");
            
            #line 32 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Put', '");
            
            #line 32 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Post']);\r\n\r\n");
            
            #line 34 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 foreach (EA.Attribute attribute in Model.Attributes.Cast<EA.Attribute>().Where(x=>!x.IsTypePrimitive())) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 35 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy = jasmine.createSpyObj<");
            
            #line 35 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type));
            
            #line default
            #line hidden
            this.Write("ServiceInterface>(['");
            
            #line 35 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Get']);\r\n\r\n");
            
            #line 37 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 } 
            
            #line default
            #line hidden
            this.Write("  matDialogRefSpy.close.and.returnValue();\r\n  \r\n  const ");
            
            #line 40 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("  = ");
            
            #line 40 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.JsObjectInitializer( Model.Attributes.Cast<EA.Attribute>().Where(x=>x.IsTypePrimitive()).ToDictionary(x=>x.Name, x=>x.GetFakeValue()) )));
            
            #line default
            #line hidden
            this.Write(" as ");
            
            #line 40 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("\r\n  \r\n  ");
            
            #line 42 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy.");
            
            #line 42 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("IdGet.and.returnValue(of(");
            
            #line 42 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  );\r\n  ");
            
            #line 43 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy.");
            
            #line 43 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Put.and.returnValue(of(");
            
            #line 43 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  );\r\n  ");
            
            #line 44 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy.");
            
            #line 44 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Post.and.returnValue(of(");
            
            #line 44 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write(")  );\r\n\r\n");
            
            #line 46 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 foreach (EA.Attribute attribute in Model.Attributes.Cast<EA.Attribute>().Where(x=>!x.IsTypePrimitive())) { 
            
            #line default
            #line hidden
            this.Write("  ");
            
            #line 47 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy.");
            
            #line 47 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Get.and.returnValue(of([] as ");
            
            #line 47 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(attribute.Type));
            
            #line default
            #line hidden
            this.Write("[]) );\r\n\r\n");
            
            #line 49 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 } 
            
            #line default
            #line hidden
            this.Write("\r\n    await TestBed.configureTestingModule({\r\n      imports: [BrowserAnimationsModule],\r\n      providers: [\r\n");
            
            #line 54 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 foreach (var entity in Model.Attributes.Cast<EA.Attribute>().Where(x=>!x.IsTypePrimitive()).Select(x=>x.Type).Concat(new string[]{Model.Name})) { 
            
            #line default
            #line hidden
            this.Write("      { provide: ");
            
            #line 55 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity));
            
            #line default
            #line hidden
            this.Write("Service, useValue: ");
            
            #line 55 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(entity.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy },\r\n");
            
            #line 56 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
 } 
            
            #line default
            #line hidden
            this.Write("      { provide: MatDialogRef<");
            
            #line 57 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent>, useValue: null },\r\n      { provide: MAT_DIALOG_DATA, useValue: null }\r\n      ],\r\n      declarations: [\r\n        \r\n      ]\r\n    })\r\n    .compileComponents();\r\n\r\n  });\r\n\r\n  it('Should init', () => {\r\n    TestBed.overrideProvider(MAT_DIALOG_DATA, { useValue: 1 });\r\n      const fixture = TestBed.createComponent(");
            
            #line 70 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent);\r\n      const component = fixture.componentInstance;\r\n      component.ngOnInit();\r\n      expect(component).toBeTruthy();\r\n  });\r\n\r\n\r\n  it('Should call update service on save for existing entity', () => {\r\n    TestBed.overrideProvider(MAT_DIALOG_DATA, { useValue: 1 });\r\n    const fixture = TestBed.createComponent(");
            
            #line 79 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent);\r\n    const component = fixture.componentInstance;\r\n    component.ok();\r\n    expect(");
            
            #line 82 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy!.");
            
            #line 82 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Put).toHaveBeenCalled();\r\n  });\r\n\r\n  \r\n  it('Should call create service on save for new entity', () => {\r\n    TestBed.overrideProvider(MAT_DIALOG_DATA, { useValue: null });\r\n    const fixture = TestBed.createComponent(");
            
            #line 88 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name));
            
            #line default
            #line hidden
            this.Write("EditComponent);\r\n    const component = fixture.componentInstance;\r\n    component.ok();\r\n    expect(");
            
            #line 91 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("ServiceSpy!.");
            
            #line 91 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"
            this.Write(this.ToStringHelper.ToStringWithCulture(Model.Name.ToCamelCase()));
            
            #line default
            #line hidden
            this.Write("Post).toHaveBeenCalled();\r\n  });\r\n\r\n\r\n \r\n\r\n\r\n});\r\n\r\n\r\n");
            return this.GenerationEnvironment.ToString();
        }
        
        #line 101 "C:\Users\David\source\repos\EA-dotnet-angular-gen\EADotnetAngularGen\Templates\Client\EditComponentSpec.tt"


public EA.Element Model { get; set; }

public ICollection<EA.Element> Entities { get; set; }


        
        #line default
        #line hidden
    }
    
    #line default
    #line hidden
    #region Base class
    /// <summary>
    /// Base class for this transformation
    /// </summary>
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.TextTemplating", "16.0.0.0")]
    public class EditComponentSpecBase
    {
        #region Fields
        private global::System.Text.StringBuilder generationEnvironmentField;
        private global::System.CodeDom.Compiler.CompilerErrorCollection errorsField;
        private global::System.Collections.Generic.List<int> indentLengthsField;
        private string currentIndentField = "";
        private bool endsWithNewline;
        private global::System.Collections.Generic.IDictionary<string, object> sessionField;
        #endregion
        #region Properties
        /// <summary>
        /// The string builder that generation-time code is using to assemble generated output
        /// </summary>
        protected System.Text.StringBuilder GenerationEnvironment
        {
            get
            {
                if ((this.generationEnvironmentField == null))
                {
                    this.generationEnvironmentField = new global::System.Text.StringBuilder();
                }
                return this.generationEnvironmentField;
            }
            set
            {
                this.generationEnvironmentField = value;
            }
        }
        /// <summary>
        /// The error collection for the generation process
        /// </summary>
        public System.CodeDom.Compiler.CompilerErrorCollection Errors
        {
            get
            {
                if ((this.errorsField == null))
                {
                    this.errorsField = new global::System.CodeDom.Compiler.CompilerErrorCollection();
                }
                return this.errorsField;
            }
        }
        /// <summary>
        /// A list of the lengths of each indent that was added with PushIndent
        /// </summary>
        private System.Collections.Generic.List<int> indentLengths
        {
            get
            {
                if ((this.indentLengthsField == null))
                {
                    this.indentLengthsField = new global::System.Collections.Generic.List<int>();
                }
                return this.indentLengthsField;
            }
        }
        /// <summary>
        /// Gets the current indent we use when adding lines to the output
        /// </summary>
        public string CurrentIndent
        {
            get
            {
                return this.currentIndentField;
            }
        }
        /// <summary>
        /// Current transformation session
        /// </summary>
        public virtual global::System.Collections.Generic.IDictionary<string, object> Session
        {
            get
            {
                return this.sessionField;
            }
            set
            {
                this.sessionField = value;
            }
        }
        #endregion
        #region Transform-time helpers
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void Write(string textToAppend)
        {
            if (string.IsNullOrEmpty(textToAppend))
            {
                return;
            }
            // If we're starting off, or if the previous text ended with a newline,
            // we have to append the current indent first.
            if (((this.GenerationEnvironment.Length == 0) 
                        || this.endsWithNewline))
            {
                this.GenerationEnvironment.Append(this.currentIndentField);
                this.endsWithNewline = false;
            }
            // Check if the current text ends with a newline
            if (textToAppend.EndsWith(global::System.Environment.NewLine, global::System.StringComparison.CurrentCulture))
            {
                this.endsWithNewline = true;
            }
            // This is an optimization. If the current indent is "", then we don't have to do any
            // of the more complex stuff further down.
            if ((this.currentIndentField.Length == 0))
            {
                this.GenerationEnvironment.Append(textToAppend);
                return;
            }
            // Everywhere there is a newline in the text, add an indent after it
            textToAppend = textToAppend.Replace(global::System.Environment.NewLine, (global::System.Environment.NewLine + this.currentIndentField));
            // If the text ends with a newline, then we should strip off the indent added at the very end
            // because the appropriate indent will be added when the next time Write() is called
            if (this.endsWithNewline)
            {
                this.GenerationEnvironment.Append(textToAppend, 0, (textToAppend.Length - this.currentIndentField.Length));
            }
            else
            {
                this.GenerationEnvironment.Append(textToAppend);
            }
        }
        /// <summary>
        /// Write text directly into the generated output
        /// </summary>
        public void WriteLine(string textToAppend)
        {
            this.Write(textToAppend);
            this.GenerationEnvironment.AppendLine();
            this.endsWithNewline = true;
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void Write(string format, params object[] args)
        {
            this.Write(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Write formatted text directly into the generated output
        /// </summary>
        public void WriteLine(string format, params object[] args)
        {
            this.WriteLine(string.Format(global::System.Globalization.CultureInfo.CurrentCulture, format, args));
        }
        /// <summary>
        /// Raise an error
        /// </summary>
        public void Error(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Raise a warning
        /// </summary>
        public void Warning(string message)
        {
            System.CodeDom.Compiler.CompilerError error = new global::System.CodeDom.Compiler.CompilerError();
            error.ErrorText = message;
            error.IsWarning = true;
            this.Errors.Add(error);
        }
        /// <summary>
        /// Increase the indent
        /// </summary>
        public void PushIndent(string indent)
        {
            if ((indent == null))
            {
                throw new global::System.ArgumentNullException("indent");
            }
            this.currentIndentField = (this.currentIndentField + indent);
            this.indentLengths.Add(indent.Length);
        }
        /// <summary>
        /// Remove the last indent that was added with PushIndent
        /// </summary>
        public string PopIndent()
        {
            string returnValue = "";
            if ((this.indentLengths.Count > 0))
            {
                int indentLength = this.indentLengths[(this.indentLengths.Count - 1)];
                this.indentLengths.RemoveAt((this.indentLengths.Count - 1));
                if ((indentLength > 0))
                {
                    returnValue = this.currentIndentField.Substring((this.currentIndentField.Length - indentLength));
                    this.currentIndentField = this.currentIndentField.Remove((this.currentIndentField.Length - indentLength));
                }
            }
            return returnValue;
        }
        /// <summary>
        /// Remove any indentation
        /// </summary>
        public void ClearIndent()
        {
            this.indentLengths.Clear();
            this.currentIndentField = "";
        }
        #endregion
        #region ToString Helpers
        /// <summary>
        /// Utility class to produce culture-oriented representation of an object as a string.
        /// </summary>
        public class ToStringInstanceHelper
        {
            private System.IFormatProvider formatProviderField  = global::System.Globalization.CultureInfo.InvariantCulture;
            /// <summary>
            /// Gets or sets format provider to be used by ToStringWithCulture method.
            /// </summary>
            public System.IFormatProvider FormatProvider
            {
                get
                {
                    return this.formatProviderField ;
                }
                set
                {
                    if ((value != null))
                    {
                        this.formatProviderField  = value;
                    }
                }
            }
            /// <summary>
            /// This is called from the compile/run appdomain to convert objects within an expression block to a string
            /// </summary>
            public string ToStringWithCulture(object objectToConvert)
            {
                if ((objectToConvert == null))
                {
                    throw new global::System.ArgumentNullException("objectToConvert");
                }
                System.Type t = objectToConvert.GetType();
                System.Reflection.MethodInfo method = t.GetMethod("ToString", new System.Type[] {
                            typeof(System.IFormatProvider)});
                if ((method == null))
                {
                    return objectToConvert.ToString();
                }
                else
                {
                    return ((string)(method.Invoke(objectToConvert, new object[] {
                                this.formatProviderField })));
                }
            }
        }
        private ToStringInstanceHelper toStringHelperField = new ToStringInstanceHelper();
        /// <summary>
        /// Helper to produce culture-oriented representation of an object as a string
        /// </summary>
        public ToStringInstanceHelper ToStringHelper
        {
            get
            {
                return this.toStringHelperField;
            }
        }
        #endregion
    }
    #endregion
}
