name: .NET


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build the solution
      run: msbuild EADotnetAngularGen.sln
    - name: Generate Sample project
      run: ./EADotnetAngularGen.exe -d "..\..\..\SampleApp" -f "..\..\..\Data\SampleModel.qea" -n SampleApp -p .* -o
      working-directory: EADotnetAngularGen\bin\Debug
    - name: Run InspectCode
      run: |
        jb inspectcode -f=text -o=inspect-report.txt SampleApp.sln
      working-directory: SampleApp
      shell: cmd
    - name: Check inspect-report.txt
      run: |
        $lineCount = (Get-Content inspect-report.txt).Count
        if ($lineCount -gt 1) {
          exit 1
        }
      working-directory: SampleApp  
    - name: Run Dotnet Test
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet-coverage collect dotnet test -f cobertura -o coverage.xml
      working-directory: SampleApp
    - uses: cjlapao/simple-badge-generator-action@v1
      with:
        badge-path: './dotnet-coverage.svg'
        badge-type: 'cobertura'
        title: 'Dotnet Coverage'
        cobertura-path: './SampleApp/coverage.xml'
    - name: Upload Dotnet badge to Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: 432ba471dc7960cd3f67f1930bbc5069
        file_path: dotnet-coverage.svg
        gist_file_name: EA-dotnet-angular-gen-dotnet-coverage.svg 
    - name: Install node_modules
      run: npm i
      working-directory: SampleApp/SampleAppClient
    - name: Update api
      run: npm run update-api
      working-directory: SampleApp/SampleAppClient
    - name: Run ng lint
      run: npm run-script ng lint
      working-directory: SampleApp/SampleAppClient
    - name: Run Angular tests
      run: npm run-script ng test -- --karma-config=karma-ci.conf.js
      working-directory: SampleApp/SampleAppClient
    - uses: cjlapao/simple-badge-generator-action@v1
      with:
        badge-path: './angular-coverage.svg'
        badge-type: 'cobertura'
        title: 'Angular Coverage'
        cobertura-path: './SampleApp/SampleAppClient/coverage/cobertura-coverage.xml'
    - name: Upload Angular badge to Gist
      uses: exuanbo/actions-deploy-gist@v1
      with:
        token: ${{ secrets.GIST_TOKEN }}
        gist_id: eee2697cb6d090e1f40427b636253eb9
        file_path: angular-coverage.svg
        gist_file_name: EA-dotnet-angular-gen-angular-coverage.svg

    - uses: actions/upload-artifact@v4
      with:
        name: Generator
        path: EADotnetAngularGen/bin/Debug/*
        
        

