name: .NET


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build the solution
      run: msbuild EADotnetAngularGen.sln
    - name: Generate Sample project
      run: ./EADotnetAngularGen.exe -d "..\..\..\SampleApp" -f "..\..\..\Data\SampleModel.qea" -n SampleApp -p .* -o
      working-directory: EADotnetAngularGen\bin\Debug
      - name: Install ReSharper Global Tools
      run: |
        dotnet tool install --global JetBrains.ReSharper.GlobalTools
    - name: Run InspectCode
      run: |
        export PATH="$PATH:/home/runner/.dotnet/tools"
        inspectcode SampleApp.sln -f=text -o=inspect-report.txt
      working-directory: EADotnetAngularGen\bin\Debug
    - name: Run Dotnet Test
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet-coverage collect dotnet test -f cobertura -o coverage.xml
      working-directory: SampleApp
    - name: Install node_modules
      run: npm i
      working-directory: SampleApp/SampleAppClient
    - name: Update api
      run: npm run update-api
      working-directory: SampleApp/SampleAppClient
    - name: Run ng lint
      run: npm run-script ng lint
      working-directory: SampleApp/SampleAppClient
    - name: Run Angular tests
      run: npm run-script ng test -- --karma-config=karma-ci.conf.js
      working-directory: SampleApp/SampleAppClient
    - uses: actions/upload-artifact@v4
      with:
        name: Generator
        path: EADotnetAngularGen/bin/Debug/*
        
        


