name: .NET


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v4
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build the solution
      run: msbuild EADotnetAngularGen.sln
    - name: Generate Sample project
      run: ./EADotnetAngularGen.exe -d "..\..\..\SampleProject" -f "..\..\..\Data\SampleModel.qea" -n SampleApp -p .* -o
      working-directory: EADotnetAngularGen\bin\Debug
    - name: Run Dotnet Test
      run: |
        dotnet tool install --global dotnet-coverage
        dotnet-coverage collect dotnet test -f cobertura -o coverage.xml
      working-directory: SampleProject
    - name: Install node_modules
      run: npm i
    - name: Run Angular tests
      run: npm run-script ng test -- --karma-config=karma-ci.conf.js
      working-directory: SampleProjectClient
    - uses: actions/upload-artifact@v4
      with:
        name: Generator
        path: EADotnetAngularGen/bin/Debug/*
        
        


