name: .NET


on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up MSBuild
      uses: microsoft/setup-msbuild@v1
    - name: Set up NuGet
      uses: NuGet/setup-nuget@v1
    - name: Restore NuGet packages
      run: nuget restore
    - name: Build the solution
      run: msbuild EADotnetAngularGen.sln
    - name: Generate Sample project
      run: EADotnetAngularGen.exe -d Output -f "..\..\..\Data\SampleModel.qea" -n SampleApp -p .*
      working-directory: EADotnetAngularGen\bin\Debug
    - uses: actions/upload-artifact@v4
      with:
        name: Generator
        path: EADotnetAngularGen/bin/Debug/*
